version: "3.7"
services:
  app:
    build:
      args:
        user: website
        uid: 1000
      context: ./
      dockerfile: ./compose/Dockerfile
    image: website
    container_name: website-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - website

  db:
    image: mysql:5.7
    container_name: website-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - website

  nginx:
    image: nginx:alpine
    container_name: website-nginx
    restart: unless-stopped
    ports:
      - 8005:80
    volumes:
      - ./:/var/www
      - ./compose/nginx:/etc/nginx/conf.d/
    networks:
      - website

networks:
  website:
    driver: bridge
